### ISSUE TITLE
Link all chest in a world

### ISSUE THREAD

**Issue by ghost** [Codisimus/PhatLoots#14]
I just wand to make a suggestion:

You can link all chest in world with a loot table with a command !

That's all :)

**Comment by Codisimus** [comment]
(I know this is late coming but I am cleaning up my GitHub issues)

The reason I do not have this feature in PhatLoots is because it would lag the server if my plugin were to search for every chest within the world.

However, there is an auto-link feature that may be of use to you. You can automatically link every chest within a world to a specific PhatLoot. This also links new chests that are placed. This feature is intended for minigames which do not allow players to place their own chests. This option can be found in the config file.
