### ISSUE TITLE
GlobalReset not working

### ISSUE THREAD

**Issue by Roadhog360** [Codisimus/PhatLoots#56]
##If set to true, when looted by one person, everyone must wait to loot it again (first person there gets the loot)
    ##If set to false, when a player loots a Chest only they must wait the specified time to loot again (everyone can have their share of loot)
    GlobalReset: true

This doesn't work.
If I have it true, when one person takes loot from a chest, everyone sees those items missing, whether it's true or false. (Yes, I tried both true and false, same outcome.
What I want it to do is so if one person took the loot, the items would not be gone for another person. That's what this option used to do, but it doesn't do that anymore, and I need it to.

**Comment by Codisimus** [comment]
It looks like this setting is from the config file. The setting in the config file is only a default setting. Any new PhatLoots will use this value. In order to change this setting for an individual loot table you can:

1. Use the command `/loot global <Name> <true|false>`
2. Toggle the setting in the loot GUI using the command `/loot gui [Name]`
3. Change the value of the setting in the PhatLoot save file located at `MinecraftServer\plugins\PhatLoots\LootTables\PhatLootName.yml`
