### ISSUE TITLE
question

### ISSUE THREAD

**Issue by justinbea** [Codisimus/PhatLoots#88]
we have an walking dead server in the make, and we have an world were people could explore to find loot, but we have an save zone in de middle of the map so people could buy plots to build something and store there loot, is it possible with in combination of PhatLoots to block an area to dont fill the chests (the save area)?

**Comment by RiCkYB-667** [comment]
As i remember you have two options:
- Link a loot to all of the existing chests on a map (using config file)
- Manually link chests (using command)

I would suggest you create the chests in the game area first (no chests anywhere else). Than enable Autolink in the config for that world. Restart the server, wait for phatloots to link all chests. When done, turn off Autolink in the config and restart server. The exsiting links should not be deleted since autolink (i assume) is just for creating the links for all existing chests, but not maintaining them. So you should be fine. All chests placed afterwards won't be linked.
If you wish to extend the number of chests in the game area, you can than easily link them manually after placement.

This is just a theory, i haven't tried this myself, but i think it should work.

**Comment by justinbea** [comment]
if i enable the autolink function they arent be saved in an file, so when i turn it off it isnt working becouse the /phatloot/chests/normal.txt file is empty with chests

**Comment by justinbea** [comment]
i have linked all of the chest i wanted to link, now when i open an chest there is loot in side of it, when i take the stuff and close the chest and reopen it, there is new stuff inside of it, is it possible to have an GLOBAL timer on the fillings per chest. so when i take stuff, that an other players the chest dont see stuff after 5 minutes of that i take the stuff out of it?

**Comment by RiCkYB-667** [comment]
This can be set in the loot table's YML file at the "Reset:" section.
Check line 10 here:
https://github.com/Codisimus/PhatLoots/blob/master/src/SampleLoot.yml

**Comment by justinbea** [comment]
if i enable the autolink function they arent be saved in an file, so when i turn it off it isnt working becouse the /phatloot/chests/normal.txt file is empty with chests, and than when i turn it off the chests will not be linked ect

**Comment by Nightshade73** [comment]
Sometimes when im linking new chests all the other chests of that Loot get cleared
I make consistent backups so I can just copy paste the coords back in and it works.

**Comment by justinbea** [comment]
@RiCkYB-667 do you have discord or something becouse it is taking to long its over 3 weeks when i started this question and i wanted to finish this gamemode with your plugin!

**Comment by RiCkYB-667** [comment]
I am not the author of this plugin, i am just a regular user trying to help wherever i can. ;)
Since i have no idea what causes your problems i couldn't comment anything.

This plugin and it's developement is abandoned for more than 2 years now (original developer is codisimus)
I suggest finding a coder yourself who can modify the source as needed.

Best of luck! ;)

**Comment by justinbea** [comment]
thread closed
